### ISSUE TITLE
on  Matterport dataset

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/soundspaces-challenge#1]
The audiovisual navigation challenge has been started, thank you for your hard work. I have downloaded the replica data set, but I have no way to download to the Matterport data set. Although I have applied for the Matterport dataset, I have never received a response. The application response of the Matterport dataset takes more time. I wonder if there is a good way to solve this problem?

**Comment by ChanganVR** [comment]
Hi @yyf17 , I remember when I requested the dataset, the reply was also a bit slow. But if you never received a response, it's probably because they missed your email. I'd suggest to email them again first and see if you can get a response in the next few days. If not, maybe I can share the cached RGBD images to avoid downloading the dataset. However, if I go with this approach, I will need to seek for legal confirmation from Facebook.

**Comment by yyf17** [comment]
Thank you for your suggestions. I have applied for Matterport data set again. I don’t know if there is any good news.

**Comment by ChanganVR** [comment]
@yyf17, have you gotten any reponse from Matterport team?

**Comment by yyf17** [comment]
@ChanganVR Thank you very much for your concern, unfortunately, I have not received any reply.

**Comment by ChanganVR** [comment]
@yyf17 I emailed the matterport3d team and CC'd you. Let's see if it was because your emails were somehow not received by them.

**Comment by yyf17** [comment]
@ChanganVR Thank you for your help, thank you very much. I am preparing for the competition.

**Comment by ChanganVR** [comment]
@yyf17 No problem. Matterport3D team has replied to me (with you being CC'd). Did you see the email? I just want to make sure, is yyf17@mails.tsinghua.edu.cn your active email address? If you still do not see the reply from them, you can email me your signed terms of use and I'll forward it to them, otherwise you can directly reply to them.

Regarding the challenge, if you run into any issues using the code, feel free to reach out to me. We can also schedule a 1-1 video chat if you think it would be helpful to you.

**Comment by yyf17** [comment]
@ChanganVR 
1) First of all, thank you for your continued help and advice.
2) The scanned copy of my data application on the Matterport3D dataset is in the attachment. I sent it to you via your mailbox <changanvr@gmail.com> and copied it to angela.dai@tum.de.
2) My valid email address is: yyf17@mails.tsinghua.edu.cn.
3) I can see the message from angela.dai@tum.de that the data application did not see, and there is no reply about whether the data application is successful.
4) Regarding the challenge, I am preparing; if I encounter difficulties, I will ask for your help in time. Video communication saves time, I prefer.

**Comment by yyf17** [comment]
@ChanganVR With your help, the application for the data set Matterport3D is successful, thank you.

**Comment by ChanganVR** [comment]
@yyf17 . No Probelm. I'm closing this issue now.
