### ISSUE TITLE
Cannot see my submission on public leaderboard

### ISSUE THREAD

**Issue by ShunqiM** [facebookresearch/soundspaces-challenge#7]
I've tried to submit JSON files for both phases and marked them as "Show on leaderboard". However, I could not see my submissions on the leaderboard. Is there any problem with my submissions?
My submission:
![image](https://user-images.githubusercontent.com/64630382/162208246-09c1feda-089d-4414-a46a-02e4ea48e0b0.png)
Leaderboard:
![image](https://user-images.githubusercontent.com/64630382/162208316-757e63a7-c210-4175-baf9-85537416cf4b.png)

**Comment by SAGNIKMJR** [comment]
It looks like the evaluation engine isn't executing your submission. Could you try submitting the json from the random agent and see what happens? If the issue is gone, you should see a 'Submitted file', 'Result file' and 'Stdout file' under Submissions, and 'Stderr file' should be None. In that case, the issue is mostly with the way you're submitting, and you need to make sure that your submission matches the random json in attributes and structure. Otherwise, I will take a look at it in a couple of days. Keep me updated.

**Comment by ShunqiM** [comment]
Random Agent JSON submitted. Still can't see anything under 'Submitted file', 'Result file' and 'Stdout file'. 
Also I've never modified `eval.py` or `agent.py`.

**Comment by SAGNIKMJR** [comment]
Got it. Will try to get back by EOD this Friday.

**Comment by SAGNIKMJR** [comment]
Update: the error doesn't seem to be on our end and instead could be an issue with the Eval AI servers. I have reached out to the EvalAI maintainers/devs about this and hope to hear back soon. In the meantime, I would suggest that you try and improve your model performance locally.

**Comment by SAGNIKMJR** [comment]
The issue seems to be fixed now. Could you try resubmitting your submission and let me know?

**Comment by ShunqiM** [comment]
I've resubmitted a random agent JSON, seems it's working now. Thanks a lot!
